import config as cfg
from .base import BaseStrategy
from analysis.indicators import add_indicators
from analysis.signals import generate_signals

class JsonStrategyLogic(BaseStrategy):
    """
    [Generic JSON Strategy Executor]
    Executes trades based on signals generated by SignalEvaluator (loaded from strategies.json).
    """
    def calculate_indicators(self, df):
        # Legacy Support: Use the old monolithic add_indicators function
        # This is required because JsonStrategy relies on the specific columns (RSI, WT, etc.)
        # generated by valid strategies.json rules.
        return add_indicators(df, self.config)

    def generate_signals(self, df):
        # Legacy Support: Use the old generate_signals which uses SignalEvaluator
        # and strategies.json loaded from file (or passed in config)
        strategy_json = self.config.get('strategy_json', None)
        return generate_signals(df, self.config, strategy_json=strategy_json)

    def get_parameter_ranges(self):
        # TODO: Parse ranges from strategies.json
        return {}
    
    def process_signal(self, state, price, signal, atr=0.0, extras=None):
        logs = []
        if extras is None: extras = {}
        
        # 1. Config & State
        # Feature Toggles (from config or strategy parameters)
        use_ts = state.config.get('use_trailing_stop', True) # Default to True for now matching Standard
        use_partial = state.config.get('use_partial_exit', True)
        
        # 2. Check Explicit Exit Signal (from JSON Rules)
        # 1 = Long Exit, 2 = Short Exit
        exit_sig = extras.get('exit_signal', 0)
        
        if state.position != 0:
            do_exit = False
            exit_reason = "StrategyExit"
            
            if state.position == 1 and (exit_sig & 1): 
                do_exit = True
            elif state.position == -1 and (exit_sig & 2): 
                do_exit = True
                
            if do_exit:
                lev_pnl = self.get_pnl(state, price)
                logs.append(state.close_position(price, exit_reason, lev_pnl))
                return logs

        # 3. Breakeven Logic (New)
        be_trigger = state.config.get('breakeven_trigger_atr', 0.0)
        
        if be_trigger > 0 and state.position != 0:
            # Check for breakeven activation
            # Breakeven offset (optional, to cover fees) = 0.0
            
            if state.position == 1:
                profit_dist = price - state.avg_entry
                target_dist = atr * be_trigger
                if profit_dist >= target_dist:
                    if state.trailing_stop_price < state.avg_entry:
                        state.trailing_stop_price = state.avg_entry
                        logs.append(f"🛡️ [Breakeven] Moving SL to Entry: {state.avg_entry}")
            
            elif state.position == -1:
                profit_dist = state.avg_entry - price
                target_dist = atr * be_trigger
                if profit_dist >= target_dist:
                     if state.trailing_stop_price == 0 or state.trailing_stop_price > state.avg_entry:
                        state.trailing_stop_price = state.avg_entry
                        logs.append(f"🛡️ [Breakeven] Moving SL to Entry: {state.avg_entry}")

        # 4. Trailing Stop Logic (State-Based)
        if use_ts and state.position != 0:
            # Fallback multiplier
            ts_mult = state.config.get('sl_multiplier', 3.0)
            if ts_mult <= 0: ts_mult = 3.0
            
            # Update Trailing Stop Price
            if state.position == 1: # Long
                new_ts = price - (atr * ts_mult)
                if new_ts > state.trailing_stop_price:
                    state.trailing_stop_price = new_ts
                
                if price <= state.trailing_stop_price:
                    lev_pnl = self.get_pnl(state, price)
                    logs.append(state.close_position(price, "TrailingStop", lev_pnl))
                    return logs
                    
            elif state.position == -1: # Short
                new_ts = price + (atr * ts_mult)
                if state.trailing_stop_price == 0 or new_ts < state.trailing_stop_price:
                    state.trailing_stop_price = new_ts
                    
                if price >= state.trailing_stop_price:
                    lev_pnl = self.get_pnl(state, price)
                    logs.append(state.close_position(price, "TrailingStop", lev_pnl))
                    return logs

        # 4. Entry / Reversal / Partial Logic
        # (Legacy Standard Logic for Partial, but simpler)
        
        if signal == 1:
            lev_pnl = self.get_pnl(state, price)
            
            # Switch Short -> Long
            if state.position == -1:
                logs.append(state.close_position(price, "Switching", lev_pnl))
            
            # Entry Long
            if state.position == 0:
                state.open_position(1, price, atr)
                logs.append(f"🔵 [LONG] Entry @ {price} | Size: ${state.balance:.2f}")

        elif signal == -1:
            lev_pnl = self.get_pnl(state, price)
            
            # Switch Long -> Short
            if state.position == 1:
                logs.append(state.close_position(price, "Switching", lev_pnl))
                
            # Entry Short
            if state.position == 0:
                state.open_position(-1, price, atr)
                logs.append(f"🔴 [SHORT] Entry @ {price} | Size: ${state.balance:.2f}")
                
        elif signal == 0:
            # Neutral / Hold / Partial Exit?
            if use_partial and state.position != 0 and not state.partial_done:
                 # Simple Partial Logic: If signal 0 (Neutral) but we are in position?
                 # Standard logic was: "If 1 -> 0, exit 50%"?
                 # No, standard logic for partial was distinct.
                 # For now, let's keep it simple: No Partial on neutral unless explicit.
                 pass
                 
        return logs
